// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGeJEmWn6BKybrWjGSeyVsJ1_NdKGNTQ0',
    appId: '1:601262614274:web:1a0d1ff7a9b727adc1841b',
    messagingSenderId: '601262614274',
    projectId: 'test-46b26',
    authDomain: 'test-46b26.firebaseapp.com',
    storageBucket: 'test-46b26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10KYT70DTH14RBKMSKvUE6ggXVSWJCEA',
    appId: '1:601262614274:android:6559e29efe44352ac1841b',
    messagingSenderId: '601262614274',
    projectId: 'test-46b26',
    storageBucket: 'test-46b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcsclLETJOV75OLHVc3syp7Y6Gv4rkI0',
    appId: '1:601262614274:ios:033d7bcb784a7df4c1841b',
    messagingSenderId: '601262614274',
    projectId: 'test-46b26',
    storageBucket: 'test-46b26.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcsclLETJOV75OLHVc3syp7Y6Gv4rkI0',
    appId: '1:601262614274:ios:6977dfa1a150f6eec1841b',
    messagingSenderId: '601262614274',
    projectId: 'test-46b26',
    storageBucket: 'test-46b26.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
